import { isPlatformBrowser } from '@angular/common';
import { Component, inject, PLATFORM_ID, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { AdminAuthDataAccess } from '../admin-auth/admin-auth.data-access';
import { AdminExperience, AdminExperienceDataAccess } from './admin-experience.data-access';

@Component({ selector: 'app-admin-experience-page', imports: [ReactiveFormsModule, RouterLink], template: `<main><h1>Admin experience</h1><section aria-label="Create experience draft"><h2>Create draft</h2><form [formGroup]="createForm" (ngSubmit)="createDraft()"><label>Organization <input formControlName="organization" /></label><label>Role <input formControlName="role" /></label><label>Summary <textarea formControlName="summary"></textarea></label><label>Start date <input type="date" formControlName="startDate" /></label><label>End date <input type="date" formControlName="endDate" /></label><button type="submit" [disabled]="createForm.invalid">Create draft</button></form></section>@if (createError()) { <p role="alert">Unable to create the experience draft. Please try again.</p> }@if (orderError()) { <p role="alert">Unable to update experience order. Please try again.</p> }@for (experience of experiences; track experience.id; let index = $index; let last = $last) { <article><h2>{{ experience.organization }}</h2><p>{{ experience.role }}</p><p>Status: {{ experience.status }}</p><button type="button" [disabled]="index === 0" [attr.aria-label]="'Move ' + experience.organization + ' up'" (click)="moveExperience(experience, 'up')">Move up</button><button type="button" [disabled]="last" [attr.aria-label]="'Move ' + experience.organization + ' down'" (click)="moveExperience(experience, 'down')">Move down</button><a [routerLink]="['/admin/experience', experience.id, 'edit']" [attr.aria-label]="'Edit ' + experience.organization">Edit</a></article> }</main>` })
export class AdminExperiencePage {
  private readonly auth = inject(AdminAuthDataAccess); private readonly experienceData = inject(AdminExperienceDataAccess); private readonly router = inject(Router); private readonly platformId = inject(PLATFORM_ID);
  protected experiences: AdminExperience[] = [];
  protected readonly createError = signal(false);
  protected readonly orderError = signal(false);
  protected readonly createForm = new FormGroup({ organization: new FormControl('', { nonNullable: true, validators: [Validators.required] }), role: new FormControl('', { nonNullable: true, validators: [Validators.required] }), summary: new FormControl('', { nonNullable: true, validators: [Validators.required] }), startDate: new FormControl('', { nonNullable: true, validators: [Validators.required] }), endDate: new FormControl('', { nonNullable: true }) });
  constructor() { if (!isPlatformBrowser(this.platformId)) return; this.auth.getSession().subscribe({ next: (session) => session.authenticated ? this.experienceData.getExperiences().subscribe((experiences) => this.experiences = experiences) : this.router.navigateByUrl('/admin/login'), error: () => this.router.navigateByUrl('/admin/login') }); }
  protected createDraft() { if (this.createForm.invalid) return; this.createError.set(false); const value = this.createForm.getRawValue(); this.experienceData.createDraft({ ...value, endDate: value.endDate || null }).subscribe({ next: (experience) => this.router.navigateByUrl(`/admin/experience/${experience.id}/edit`), error: () => this.createError.set(true) }); }
  protected moveExperience(experience: AdminExperience, direction: 'up' | 'down') { this.orderError.set(false); this.experienceData.moveExperience(experience.id, direction).subscribe({ next: (experiences) => this.experiences = experiences, error: () => this.orderError.set(true) }); }
}
