import { BadRequestException, Body, Controller, Get, Param, ParseUUIDPipe, Patch, Post, UseGuards } from '@nestjs/common';
import { ApiBody, ApiCreatedResponse, ApiForbiddenResponse, ApiNotFoundResponse, ApiOkResponse, ApiTags, ApiUnauthorizedResponse } from '@nestjs/swagger';
import { CredentialService } from '../credentials/credential.service.js';
import { AdminSessionGuard } from './admin-session.guard.js';
import { AdminCredentialDetailResponseDto } from './admin-credential-detail-response.dto.js';
import { AdminCredentialResponseDto } from './admin-credential-response.dto.js';
import { TrustedOriginGuard } from './trusted-origin.guard.js';
import { UpdateCredentialContentDto } from './update-credential-content.dto.js';
import { UpdateCredentialStatusDto } from './update-credential-status.dto.js';
import { CreateCredentialDraftDto } from './create-credential-draft.dto.js';
import { UpdateCredentialOrderDto } from './update-credential-order.dto.js';
const calendarDate = (value: string) => {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) return false;
  const [year, month, day] = value.split('-').map(Number);
  const date = new Date(Date.UTC(year, month - 1, day));
  return date.getUTCFullYear() === year && date.getUTCMonth() === month - 1 && date.getUTCDate() === day;
};
@ApiTags('admin') @Controller('admin/credentials')
export class AdminCredentialsController { constructor(private readonly credentials: CredentialService) {} @Get() @UseGuards(AdminSessionGuard) @ApiOkResponse({ type: AdminCredentialResponseDto, isArray: true }) @ApiUnauthorizedResponse() list() { return this.credentials.getAdminCredentials(); } @Post() @UseGuards(AdminSessionGuard, TrustedOriginGuard) @ApiBody({ type: CreateCredentialDraftDto }) @ApiCreatedResponse({ type: AdminCredentialDetailResponseDto }) @ApiUnauthorizedResponse() @ApiForbiddenResponse() createDraft(@Body() body: CreateCredentialDraftDto) { return this.credentials.createDraft(this.validContent(body)); } @Get(':id') @UseGuards(AdminSessionGuard) @ApiOkResponse({ type: AdminCredentialDetailResponseDto }) @ApiUnauthorizedResponse() @ApiNotFoundResponse() detail(@Param('id', new ParseUUIDPipe({ version: '4' })) id: string) { return this.credentials.getAdminCredential(id); } @Patch(':id/content') @UseGuards(AdminSessionGuard, TrustedOriginGuard) @ApiBody({ type: UpdateCredentialContentDto }) @ApiOkResponse({ type: AdminCredentialDetailResponseDto }) @ApiUnauthorizedResponse() @ApiForbiddenResponse() @ApiNotFoundResponse() update(@Param('id', new ParseUUIDPipe({ version: '4' })) id: string, @Body() body: UpdateCredentialContentDto) { return this.credentials.updateContent(id, this.validContent(body)); } @Patch(':id/status') @UseGuards(AdminSessionGuard, TrustedOriginGuard) @ApiBody({ type: UpdateCredentialStatusDto }) @ApiOkResponse({ type: AdminCredentialDetailResponseDto }) @ApiUnauthorizedResponse() @ApiForbiddenResponse() @ApiNotFoundResponse() updateStatus(@Param('id', new ParseUUIDPipe({ version: '4' })) id: string, @Body() body: UpdateCredentialStatusDto) { if (!['draft', 'published', 'archived'].includes(body?.status)) throw new BadRequestException('Credential status must be draft, published, or archived.'); return this.credentials.updateStatus(id, body.status); } @Patch(':id/order') @UseGuards(AdminSessionGuard, TrustedOriginGuard) @ApiBody({ type: UpdateCredentialOrderDto }) @ApiOkResponse({ type: AdminCredentialResponseDto, isArray: true }) @ApiUnauthorizedResponse() @ApiForbiddenResponse() @ApiNotFoundResponse() updateOrder(@Param('id', new ParseUUIDPipe({ version: '4' })) id: string, @Body() body: UpdateCredentialOrderDto) { if (body?.direction !== 'up' && body?.direction !== 'down') throw new BadRequestException('Credential order direction must be up or down.'); return this.credentials.moveCredential(id, body.direction); } private validContent(body: UpdateCredentialContentDto | CreateCredentialDraftDto) { const name = typeof body?.name === 'string' ? body.name.trim() : ''; const issuer = typeof body?.issuer === 'string' ? body.issuer.trim() : ''; const issuedOn = typeof body?.issuedOn === 'string' ? body.issuedOn : ''; if (!name || !issuer || !calendarDate(issuedOn)) throw new BadRequestException('Credential name, issuer, and a valid issued date are required.'); return { name, issuer, issuedOn }; } }
